<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta content="utf-8" http-equiv="encoding">
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body class="page-empty <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
        <div>
            <?php echo $this->getChildHtml('content') ?>
        </div>
        <footer>
            <?php echo $this->getChildHtml('before_body_end') ?>
        </footer>
    </body>
</html>
