<!DOCTYPE HTML>
<html>
    <head>
        <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
        <meta content="utf-8" http-equiv="encoding">
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <?php echo $this->getChildHtml('global_notices') ?>
        <header>
            <?php echo $this->getChildHtml('header') ?>
        </header>
        <nav></nav>

        <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
            <aside class="col-left sidebar col-left-first"><?php echo $_leftContent; ?></aside>
        <?php endif; ?>

        <section>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
        </section>

        <aside class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></aside>

        <footer>
            <?php echo $this->getChildHtml('footer_before') ?>
            <?php echo $this->getChildHtml('footer') ?>
        </footer>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
